services:
  - type: web
    name: online-exam-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: FRONTEND_URL
        value: https://online-exam-frontend.onrender.com

  - type: web
    name: online-exam-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18